# -*- coding: utf-8 -*-
"""Disease_Diagnosis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ttC3tzc49sRwJ3-4XyqN8qDWrkE6FT7r
"""
import os
import pathlib
import textwrap

import google.generativeai as genai

from IPython.display import display
from IPython.display import Markdown


def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

GOOGLE_API_KEY = 'AIzaSyAvw5v7lTEkG06xwNTNG69outIzHKV4yO0'


genai.configure(api_key=GOOGLE_API_KEY)

#model = genai.GenerativeModel('gemini-pro')
#This part only takes string input as prpmts
#response = model.generate_content("What is 2 + 2?")

#markdown_object = to_markdown(response.text)
#Convert markdown object to string: 
#print(F"Output: {markdown_object._repr_markdown_()}")

#HERE WE USING IMAGES WITH PROMPTS. 

import PIL.Image

#Add your image to disease-diagnosis/images
img = PIL.Image.open('images/test.png')


#Use the gemini pro vision model for image and text input prompts
model = genai.GenerativeModel('gemini-pro-vision')

response = model.generate_content(["What is in the picture? ",img], stream=True)
response.resolve()

markdown_object = to_markdown(response.text)
print(F"Output: {markdown_object._repr_markdown_()}")

