# -*- coding: utf-8 -*-
"""Disease_Diagnosis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ttC3tzc49sRwJ3-4XyqN8qDWrkE6FT7r
"""
import os
import pathlib
import textwrap

import google.generativeai as genai

from IPython.display import display
from IPython.display import Markdown


def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

GOOGLE_API_KEY = 'AIzaSyAvw5v7lTEkG06xwNTNG69outIzHKV4yO0'


genai.configure(api_key=GOOGLE_API_KEY)

model = genai.GenerativeModel('gemini-pro')
response = model.generate_content("What is 2 + 2?")

markdown_object = to_markdown(response.text)
#Convert markdown object to string: 
print(F"Output: {markdown_object._repr_markdown_()}")

# Commented out IPython magic to ensure Python compatibility.
# %%time
# response = model.generate_content("What is the meaning of life?")
#

#to_markdown(response.text)

# import PIL.Image

# img = PIL.Image.open('image.jpg')
# img

# model = genai.GenerativeModel('gemini-pro-vision')

# response = model.generate_content(["What is in the picture? ",img], stream=True)
# response.resolve()

# to_markdown(response.text)

