# -*- coding: utf-8 -*-
"""Disease_Diagnosis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ttC3tzc49sRwJ3-4XyqN8qDWrkE6FT7r
"""
import streamlit as st
import streamlit.components.v1 as components
import textwrap

import google.generativeai as genai

from IPython.display import display
from IPython.display import Markdown

template = """
<div>
    <input type="text" id="userInput" placeholder="Enter text here">
    <button onclick="sendInputToPython()">Submit</button>
</div>
<script>
    function sendInputToPython() {
        const inputValue = document.getElementById("userInput").value;
        Streamlit.setComponentValue(inputValue); 
    }
</script>

        """

returned_val = components.html(template, height=200)
st.write(returned_val.text)






